### ISSUE TITLE
Amélioration du design de la liste des talks

### ISSUE THREAD

**Issue by zyhou** [aperowebnancy/aperowebnancy-website#46]
La page qui liste les précédents talks est une liste qui met un talk les un sous les autres, voir:

![image](https://user-images.githubusercontent.com/2212144/94834591-d84f5e00-0410-11eb-9c30-9ffccf84498b.png)

Nous n'avons pas énormément d'élément à afficher pour chaque talk. Il serait intéressant de mettre deux (trois?) talks sur une ligne, sous forme de carte, un peu comme dans la page speakers, voir:

![image](https://user-images.githubusercontent.com/2212144/94834980-5dd30e00-0411-11eb-9065-4e7ab9561a7f.png)
(mais sur deux colonnes)

**Comment by zyhou** [comment]
@aymericingargiola a déjà commencé à travailler sur le sujet, une preview de son travail:

![image](https://user-images.githubusercontent.com/2212144/94835263-c4582c00-0411-11eb-8d51-3dea5e494009.png)

**Comment by aymericingargiola** [comment]
@zyhou Pour mettre en avant le talk du jour on pourrait faire passer cette carte en full width à la place de la moitié comme les autres, j'ai tenté quelque chose :
![image](https://user-images.githubusercontent.com/49032117/94898514-fd37e580-0491-11eb-9c58-82bed0b746db.png)

**Comment by zyhou** [comment]
Encore merci pour ta participation :+1:

**Comment by zyhou** [comment]
Encore merci pour ta participation :+1:

**Comment by zyhou** [comment]
Encore merci pour ta participation :+1:
